### ISSUE TITLE
failed to validate LinearAxis gdal error

### ISSUE THREAD

**Issue by AlphaGxx** [hectornieto/pyTVDI#1]
1.First gdal import need to replace 

import gdal
↓
from osgeo import gdal

2.Validate LineAxis

I want to  run  example  but it's give me the error below

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-6f26e7d9cfdb> in <module>
     35 ramp = figure(tools="", y_range = [0, 1], x_range = [low_flux,high_flux], plot_width = 650, plot_height=100)
     36 ramp.toolbar_location=None
---> 37 ramp.yaxis.visible = None
     38 ramp.rect(x=y, y=0.5, color=colortable, width=dy, height = 1)
     39 

c:\python39\lib\site-packages\bokeh-2.3.1-py3.9.egg\bokeh\models\plots.py in __setattr__(self, attr, value)
    736     def __setattr__(self, attr, value):
    737         for x in self:
--> 738             setattr(x, attr, value)
    739     def __getattribute__(self, attr):
    740         if attr in dir(list):

c:\python39\lib\site-packages\bokeh-2.3.1-py3.9.egg\bokeh\core\has_props.py in __setattr__(self, name, value)
    296 
    297         if name in props or (descriptor is not None and descriptor.fset is not None):
--> 298             super().__setattr__(name, value)
    299         else:
    300             matches, text = difflib.get_close_matches(name.lower(), props), "similar"

c:\python39\lib\site-packages\bokeh-2.3.1-py3.9.egg\bokeh\core\property\descriptors.py in __set__(self, obj, value, setter)
    550             raise RuntimeError(f"{class_name}.{self.name} is a readonly property")
    551 
--> 552         self._internal_set(obj, value, setter=setter)
    553 
    554     def __delete__(self, obj):

c:\python39\lib\site-packages\bokeh-2.3.1-py3.9.egg\bokeh\core\property\descriptors.py in _internal_set(self, obj, value, hint, setter)
    782 
    783         """
--> 784         value = self.property.prepare_value(obj, self.name, value)
    785         old = self._get(obj)
    786         self._real_set(obj, old, value, hint=hint, setter=setter)

c:\python39\lib\site-packages\bokeh-2.3.1-py3.9.egg\bokeh\core\property\bases.py in prepare_value(self, owner, name, value)
    348         else:
    349             obj_repr = owner if isinstance(owner, HasProps) else owner.__name__
--> 350             raise ValueError(f"failed to validate {obj_repr}.{name}: {error}")
    351 
    352         if isinstance(owner, HasProps):

ValueError: failed to validate LinearAxis(id='1118', ...).visible: expected a value of type bool or bool_, got None of type NoneType

​

I don't know what happen?

**Comment by hectornieto** [comment]
I would suggest you to use anaconda and install library dependencies (e.g. gdal, bokeh, ...) with conda

**Comment by yulan0215** [comment]
> 1.First gdal import need to replace
> 
> import gdal ↓ from osgeo import gdal
> 
> 2.Validate LineAxis

Hi:

I am sorry I have a question that how did you do: 

1.First gdal import need to replace

import gdal
↓
from osgeo import gdal          this step? I mean, the file was saved in the *.egg file but I did not know how to modify the "import gdal" into from osgeo import gdal? 
Thx!

**Comment by hectornieto** [comment]
I do not understand your issue,

Please follow the suggestion I made above
